name: Workflow Manual

on:
  workflow_dispatch:

jobs:

  primer_job:
    name: Primer Job
    runs-on: ubuntu-latest

    steps:
      - name: Primer step
        run: echo "Hello, world! "

  segundo_job:
    name: Segundo Job
    runs-on: ubuntu-latest
    needs: [primer_job]

    steps:
      - name: Primer step
        run: echo "Hello, world! - Desde el segundo Job "

      - name: Segundo step
        run: echo "Hello, world! - Otro step más"

